<a href="https://colab.research.google.com/github/Laisgraca/Pandas/blob/main/Aula02pd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Criando um Dataframe e Renomeando

---

# Importar a Biblioteca

In [1]:
#importando a biblioteca
import pandas as pd

# Criando um DataFrame

In [5]:
alunos_df = pd.DataFrame({
    'nome': ['Aya', 'John', 'Denis'],
    'sexo': ['M', 'F', 'M'],
    'idade': [22, 26, 28]
})

In [6]:
alunos_df

    nome sexo  idade
0    Aya    M     22
1   John    F     26
2  Denis    M     28

In [7]:
alunos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    3 non-null      object
 1   sexo    3 non-null      object
 2   idade   3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

#Renomenado as colunas de um DataFrame

In [8]:
alunos_df.columns # Lista o nome de todas as colunas do DataFrame

Index(['nome', 'sexo', 'idade'], dtype='object')

In [9]:
list(alunos_df.columns) #converter para uma Lista

['nome', 'sexo', 'idade']

In [10]:
alunos_df_renomeado= alunos_df.rename(columns={
    'nome':'Nome do Aluno',
    'idade': 'Idade' # Renomeia a coluna 'idade' para 'Idade'
})

In [11]:
alunos_df_renomeado

  Nome do Aluno sexo  Idade
0           Aya    M     22
1          John    F     26
2         Denis    M     28

In [14]:
alunos_df

    nome sexo  idade
0    Aya    M     22
1   John    F     26
2  Denis    M     28

Note que o parâmetro rename cria cópia e não altera a tabela original(alunos_df), para alterar de forma definitiva utilizamos o método inplace= True

In [17]:
alunos_df.rename(columns={
    'nome':'Nome do Aluno',
    'idade': 'Idade' # Renomeia a coluna 'idade' para 'Idade de forma definitiva'
}, inplace=True)

In [18]:
alunos_df

  Nome do Aluno sexo  Idade
0           Aya    M     22
1          John    F     26
2         Denis    M     28

In [21]:
alunos_df.columns= ['NOME','SEXO','IDADE'] #Renomear todas as colunas de uma vez

In [22]:
alunos_df

    NOME SEXO  IDADE
0    Aya    M     22
1   John    F     26
2  Denis    M     28